const { LEAD_STATUS } = require('./lead-status');

const PIPELINE_SEQUENCE = [
  LEAD_STATUS.DISCOVERED,
  LEAD_STATUS.ENRICHED,
  LEAD_STATUS.QUALIFIED,
  LEAD_STATUS.MESSAGE_READY,
  LEAD_STATUS.QA_APPROVED,
  LEAD_STATUS.SENT,
  LEAD_STATUS.ENGAGED,
  LEAD_STATUS.FOLLOWUP_DUE,
  LEAD_STATUS.OPPORTUNITY,
  LEAD_STATUS.WON,
  LEAD_STATUS.LOST,
  LEAD_STATUS.BLOCKED
];

const ALLOWED_TRANSITIONS = Object.freeze({
  [LEAD_STATUS.DISCOVERED]: [LEAD_STATUS.ENRICHED, LEAD_STATUS.BLOCKED],
  [LEAD_STATUS.ENRICHED]: [LEAD_STATUS.QUALIFIED, LEAD_STATUS.BLOCKED],
  [LEAD_STATUS.QUALIFIED]: [LEAD_STATUS.MESSAGE_READY, LEAD_STATUS.BLOCKED],
  [LEAD_STATUS.MESSAGE_READY]: [LEAD_STATUS.QA_APPROVED, LEAD_STATUS.BLOCKED],
  [LEAD_STATUS.QA_APPROVED]: [LEAD_STATUS.SENT, LEAD_STATUS.BLOCKED],
  [LEAD_STATUS.SENT]: [LEAD_STATUS.ENGAGED, LEAD_STATUS.FOLLOWUP_DUE, LEAD_STATUS.LOST],
  [LEAD_STATUS.ENGAGED]: [LEAD_STATUS.OPPORTUNITY, LEAD_STATUS.FOLLOWUP_DUE, LEAD_STATUS.LOST],
  [LEAD_STATUS.FOLLOWUP_DUE]: [LEAD_STATUS.SENT, LEAD_STATUS.ENGAGED, LEAD_STATUS.LOST],
  [LEAD_STATUS.OPPORTUNITY]: [LEAD_STATUS.WON, LEAD_STATUS.LOST],
  [LEAD_STATUS.WON]: [],
  [LEAD_STATUS.LOST]: [],
  [LEAD_STATUS.BLOCKED]: []
});

function canTransition(currentStatus, nextStatus) {
  if (!currentStatus) return nextStatus === LEAD_STATUS.DISCOVERED;
  return (ALLOWED_TRANSITIONS[currentStatus] || []).includes(nextStatus);
}

module.exports = {
  PIPELINE_SEQUENCE,
  ALLOWED_TRANSITIONS,
  canTransition
};
